name: LanguageAPI
main: Language\Language
version: 1.0.0
authors:
  - Natha
  - Playek
api: 3.17
commands:
  language:
    description: change your language
    permission: default
    usage: /language list
    aliases: [lang]
